export const exerciseImages: Record<
  "back" | "chest" | "biceps" | "triceps" | "legs" | "shoulders",
  any
> = {
  back: {
    deadlift: require("../assets/images/exercises/back/deadlift1.png"),
    barbell_row: require("../assets/images/exercises/back/barbell_row1.png"),
    cable_row: require("../assets/images/exercises/back/cable_row1.png"),
    lat_pullover: require("../assets/images/exercises/back/lat_pullover1.png"),
    neutral_grip_lat_pulldown: require("../assets/images/exercises/back/neutral_grip_lat_pulldown1.png"),
    one_arm_dumbbell_row: require("../assets/images/exercises/back/one_arm_dumbbell_row1.png"),
    wide_grip_lat_pulldown: require("../assets/images/exercises/back/wide_grip_lat_pulldown1.png"),
  },
  chest: {
    bench_press: require("../assets/images/exercises/chest/bench_press1.png"),
    incline_bench_press: require("../assets/images/exercises/chest/incline_bench_press1.png"),
    dumbbell_press: require("../assets/images/exercises/chest/dumbbell_press1.png"),
    pec_fly: require("../assets/images/exercises/chest/pec_fly1.png"),
    machine_chest_press: require("../assets/images/exercises/chest/machine_chest_press1.png"),
    chest_press: require("../assets/images/exercises/chest/chest_press.png"),
  },
  biceps: {
    barbell_curl: require("../assets/images/exercises/biceps/barbell_curl1.png"),
    dumbbell_curl: require("../assets/images/exercises/biceps/dumbbell_curl1.png"),
    dumbbell_incline_curl: require("../assets/images/exercises/biceps/dumbbell_incline_curl1.png"),
    dumbbell_preacher_curl: require("../assets/images/exercises/biceps/dumbbell_preacher_curl1.png"),
    faceaway_bayesian_cable_curl: require("../assets/images/exercises/biceps/faceaway_bayesian_cable_curl1.png"),
    hammer_preacher_curl: require("../assets/images/exercises/biceps/hammer_preacher_curl1.png"),
    machine_preacher_curl: require("../assets/images/exercises/biceps/machine_preacher_curl1.png"),
  },
  triceps: {
    triceps_pushdown: require("../assets/images/exercises/triceps/triceps_pushdown1.png"),
    overhead_cable_extension: require("../assets/images/exercises/triceps/overhead_cable_extension1.png"),
    db_french_press: require("../assets/images/exercises/triceps/db_french_press1.png"),
    cable_kickback: require("../assets/images/exercises/triceps/cable_kickback1.png"),
    machine_dips: require("../assets/images/exercises/triceps/machine_dips1.png"),
  },
  shoulders: {
    db_lateral_raise: require("../assets/images/exercises/shoulders/db_lateral_raise1.png"),
    overhead_press: require("../assets/images/exercises/shoulders/overhead_press1.png"),
    db_overhead_press: require("../assets/images/exercises/shoulders/db_overhead_press1.png"),
    machine_shoulder_press: require("../assets/images/exercises/shoulders/machine_shoulder_press1.png"),
    standing_machine_lateral_raise: require("../assets/images/exercises/shoulders/standing_machine_lateral_raise1.png"),
    cable_lateral_raise: require("../assets/images/exercises/shoulders/cable_lateral_raise1.png"),
    reverse_pec_dec: require("../assets/images/exercises/shoulders/reverse_pec_dec1.png"),
    rope_face_pull: require("../assets/images/exercises/shoulders/rope_face_pull1.png"),
    lateral_raise: require("../assets/images/exercises/shoulders/lateral_raise.png"),
  },
  legs: {
    squats: require("../assets/images/exercises/legs/squats1.png"),
    smith_machine_squat: require("../assets/images/exercises/legs/smith_machine_squat1.png"),
    degree_45_leg_press: require("../assets/images/exercises/legs/degree_45_leg_press1.png"),
    leg_extension: require("../assets/images/exercises/legs/leg_extension1.png"),
    romanian_deadlift: require("../assets/images/exercises/legs/romanian_deadlift1.png"),
    seated_leg_curl: require("../assets/images/exercises/legs/seated_leg_curl1.png"),
    hip_adductions: require("../assets/images/exercises/legs/hip_adductions1.png"),
    hip_abductions: require("../assets/images/exercises/legs/hip_abductions1.png"),
  },
}
