export const exerciseImages: Record<
  "back" | "chest" | "biceps" | "triceps" | "legs" | "shoulders",
  any
> = {
  back: {
    deadlift: require("../assets/images/exercises/back/deadlift.png"),
    barbell_row: require("../assets/images/exercises/back/barbell_row.png"),
    cable_row: require("../assets/images/exercises/back/cable_row.png"),
    lat_pullover: require("../assets/images/exercises/back/lat_pullover.png"),
    neutral_grip_lat_pulldown: require("../assets/images/exercises/back/neutral_grip_lat_pulldown.png"),
    one_arm_dumbbell_row: require("../assets/images/exercises/back/one_arm_dumbbell_row.png"),
    wide_grip_lat_pulldown: require("../assets/images/exercises/back/wide_grip_lat_pulldown.png"),
  },
  chest: {
    bench_press: require("../assets/images/exercises/chest/bench_press.png"),
    incline_bench_press: require("../assets/images/exercises/chest/incline_bench_press.png"),
    dumbbell_press: require("../assets/images/exercises/chest/dumbbell_press.png"),
    pec_fly: require("../assets/images/exercises/chest/pec_fly.png"),
    machine_chest_press: require("../assets/images/exercises/chest/machine_chest_press.png"),
  },
  biceps: {
    barbell_curl: require("../assets/images/exercises/biceps/barbell_curl.png"),
    dumbbell_curl: require("../assets/images/exercises/biceps/dumbbell_curl.png"),
    dumbbell_incline_curl: require("../assets/images/exercises/biceps/dumbbell_incline_curl.png"),
    dumbbell_preacher_curl: require("../assets/images/exercises/biceps/dumbbell_preacher_curl.png"),
    faceaway_bayesian_cable_curl: require("../assets/images/exercises/biceps/faceaway_bayesian_cable_curl.png"),
    hammer_preacher_curl: require("../assets/images/exercises/biceps/hammer_preacher_curl.png"),
    machine_preacher_curl: require("../assets/images/exercises/biceps/machine_preacher_curl.png"),
  },
  triceps: {
    triceps_pushdown: require("../assets/images/exercises/triceps/triceps_pushdown.png"),
    overhead_cable_extension: require("../assets/images/exercises/triceps/overhead_cable_extension.png"),
    db_french_press: require("../assets/images/exercises/triceps/db_french_press.png"),
    cable_kickback: require("../assets/images/exercises/triceps/cable_kickback.png"),
    machine_dips: require("../assets/images/exercises/triceps/machine_dips.png"),
  },
  shoulders: {
    db_lateral_raise: require("../assets/images/exercises/shoulders/db_lateral_raise.png"),
    overhead_press: require("../assets/images/exercises/shoulders/overhead_press.png"),
    db_overhead_press: require("../assets/images/exercises/shoulders/db_overhead_press.png"),
    machine_shoulder_press: require("../assets/images/exercises/shoulders/machine_shoulder_press.png"),
    standing_machine_lateral_raise: require("../assets/images/exercises/shoulders/standing_machine_lateral_raise.png"),
    cable_lateral_raise: require("../assets/images/exercises/shoulders/cable_lateral_raise.png"),
    reverse_pec_dec: require("../assets/images/exercises/shoulders/reverse_pec_dec.png"),
    rope_face_pull: require("../assets/images/exercises/shoulders/rope_face_pull.png"),
  },
  legs: {
    squats: require("../assets/images/exercises/legs/squats.png"),
    smith_machine_squat: require("../assets/images/exercises/legs/smith_machine_squat.png"),
    degree_45_leg_press: require("../assets/images/exercises/legs/degree_45_leg_press.png"),
    leg_extension: require("../assets/images/exercises/legs/leg_extension.png"),
    romanian_deadlift: require("../assets/images/exercises/legs/romanian_deadlift.png"),
    seated_leg_curl: require("../assets/images/exercises/legs/seated_leg_curl.png"),
    hip_adductions: require("../assets/images/exercises/legs/hip_adductions.png"),
    hip_abductions: require("../assets/images/exercises/legs/hip_abductions.png"),
  },
}
